[plugin]
repository = "https://github.com/Paparogue/Tabnado.git"
commit = "c4f49dc2177bdeda615633857e77cd43f67322cc"
project_path = "Tabnado"
owners = ["Paparogue", "Mentor Btw"]
changelog = "Fixed several issues with some of the targeting logic."
