[plugin]
repository = "https://github.com/Paparogue/Tabnado.git"
commit = "4d1901aa88359331eab4731dac78b0d9290ee8a7"
project_path = "Tabnado"
owners = ["Paparogue", "Mentor Btw"]
changelog = "Bugfixes, Tab Target Reset Methods added, Fixed Key Registration, Fixed ClearTargetTable"
