[plugin]
repository = "https://github.com/Paparogue/Tabnado.git"
commit = "8e2e08f83f4d487a648172f5f06a11a95131154d"
project_path = "Tabnado"
owners = ["Paparogue"]
changelog = "Bugfixes, Tab Target Reset Method added."
