[plugin]
repository = "https://github.com/Paparogue/Tabnado.git"
commit = "be38921041fd22d95eb98d8208c2bedbfd36450f"
project_path = "Tabnado"
owners = ["Paparogue", "Mentor Btw"]
changelog = "Added alternative cycling method, added no target causes clear option, hide debug options."
