[plugin]
repository = "https://github.com/Paparogue/Tabnado.git"
commit = "345e6e59c8eba2d27b979708078ed08c53d1e50b"
project_path = "Tabnado"
owners = ["Paparogue", "Mentor Btw"]
changelog = "New Options, Bugfixes and wonderful things."
