[plugin]
repository = "https://github.com/Paparogue/Tabnado.git"
commit = "9cb5f5d32f2362173e552e784684b33da0313629"
project_path = "Tabnado"
owners = ["Paparogue", "Mentor Btw"]
changelog = "Moved the Camera and GroupManager Init Call, fixed some descriptions."
