[plugin]
repository = "https://github.com/Paparogue/Tabnado.git"
commit = "7b65563a009d9f8558f07669638bd84593daef05"
project_path = "Tabnado"
owners = ["Paparogue", "Mentor Btw"]
changelog = "More bugfixes"
