[plugin]
repository = "https://github.com/Paparogue/Tabnado.git"
commit = "f5e448968d6d7b8e352e8215d528dfce5d593c20"
project_path = "Tabnado"
owners = ["Paparogue", "Mentor Btw"]
changelog = "Bugfixes, Added Raycast Percent"
