[plugin]
repository = "https://github.com/Paparogue/Tabnado.git"
commit = "aee2a191ef86e4cb37a4b7790e0a96a76a14914f"
project_path = "Tabnado"
owners = ["Paparogue", "Mentor Btw"]
changelog = "FPS Bugfixes"
