[plugin]
repository = "https://github.com/Paparogue/Tabnado.git"
commit = "2ba1b43c53da088675c39a5fb41f537c0395e1eb"
project_path = "Tabnado"
owners = ["Paparogue", "Mentor Btw"]
changelog = "Fixed an issue with Raycasts on flying enemies"
